"""Deterministic PDF renderer for Niskava investigation audit trail reports.

Uses fpdf2 (pure-Python, zero C-extensions) to produce institutional-grade PDF
documents. This module has exactly one public entry point:

    render_investigation_pdf(params: Dict[str, Any], output_dir: Optional[Path] = None) -> str

All data must be pre-computed and passed in via `params`. No LLM, no API calls.
"""

from __future__ import annotations

import os
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ─── Constants ───────────────────────────────────────────────────────────────

NON_ADVISORY_DISCLAIMER: str = (
    "NON-ADVISORY DISCLAIMER: This document is an autonomous market intelligence audit "
    "trail generated by Niskava Agent. It does NOT constitute financial advice, "
    "investment recommendations, or solicitation to buy or sell any security. "
    "All findings are strictly informational and investigative in nature."
)

_NISKAVA_BLUE = (13, 71, 161)      # Institutional Navy Blue #0D47A1
_SUPPORTED_GREEN = (27, 94, 32)     # Emerald Green #1B5E20
_UNCERTAIN_ORANGE = (230, 81, 0)    # Amber/Orange #E65100
_CONTRADICTED_RED = (183, 28, 28)   # Crimson Red #B71C1C
_LIGHT_GRAY = (245, 245, 245)
_DARK_GRAY = (66, 66, 66)

_CALLOUT_BG = {
    "info": (238, 242, 250),      # Soft Navy Blue
    "warning": (255, 248, 225),   # Soft Amber
    "success": (232, 245, 233),   # Soft Emerald
}
_CALLOUT_BORDER = {
    "info": _NISKAVA_BLUE,
    "warning": _UNCERTAIN_ORANGE,
    "success": _SUPPORTED_GREEN,
}


def _clean_text(text: Any, single_line: bool = False) -> str:
    """Sanitize string for core Helvetica Latin-1 font in fpdf2."""
    if text is None:
        return ""
    s = str(text)
    if single_line:
        s = s.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--",
        "\u2026": "...", "\u00a0": " ",
        "\u2022": "-", "\u2023": ">", "\u25aa": "-",
        "\u2192": "->", "\u2190": "<-", "\u2191": "+", "\u2193": "-",
        "\u2248": "~", "\u2260": "!=",
        "σ": "sigma", "≥": ">=", "≤": "<=", "±": "+/-",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode("latin-1", errors="replace").decode("latin-1")


def _sanitize_session_short(session_id: Optional[str]) -> str:
    """Extract a 6-character uppercase alphanumeric session suffix. Defaults to '000000'."""
    if not session_id:
        return "000000"
    clean = "".join(c for c in str(session_id) if c.isalnum()).upper()
    if not clean:
        return "000000"
    if len(clean) >= 6:
        return clean[-6:]
    return clean.rjust(6, "0")


def _verification_color(status: str) -> tuple[int, int, int]:
    mapping = {
        "SUPPORTED": _SUPPORTED_GREEN,
        "UNCERTAIN": _UNCERTAIN_ORANGE,
        "CONTRADICTED": _CONTRADICTED_RED,
    }
    return mapping.get(status.upper(), _DARK_GRAY)


class _NiskavaReportPDF(FPDF):
    """FPDF subclass with Niskava header and mandatory non-advisory footer on every page."""

    def __init__(self, ticker: str, session_id: str) -> None:
        super().__init__()
        self.set_compression(False)
        self._ticker = ticker
        self._session_id = session_id

    def header(self) -> None:
        # Blue banner across top
        self.set_fill_color(*_NISKAVA_BLUE)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10.5)
        self.set_xy(10, 4)
        clean_header = _clean_text(
            f"NISKAVA MARKET INTELLIGENCE  |  {self._ticker}  |  {self._session_id}"
        )
        self.cell(190, 10, clean_header, align="L")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self) -> None:
        self.set_y(-22)
        # Disclaimer callout box
        self.set_fill_color(255, 243, 224)
        self.set_draw_color(230, 81, 0)
        self.rect(10, self.get_y(), 190, 14, "FD")
        self.set_font("Helvetica", "", 6.5)
        self.set_text_color(*_UNCERTAIN_ORANGE)
        self.set_xy(12, self.get_y() + 1)
        self.multi_cell(186, 3.5, NON_ADVISORY_DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(150, 150, 150)
        self.set_font("Helvetica", "", 7)
        self.set_xy(10, self.get_y() + 1)
        self.cell(190, 4, f"Generated by Niskava Agent  |  Page {self.page_no()}", align="R")


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.set_fill_color(*_LIGHT_GRAY)
    pdf.cell(190, 6.5, f"  {_clean_text(title)}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1.5)


def _render_callout_box(
    pdf: FPDF,
    text: str,
    title: Optional[str] = None,
    style: str = "info",
) -> None:
    """Render an institutional callout box with a colored left-accent bar."""
    if not text:
        return
    bg_color = _CALLOUT_BG.get(style, _CALLOUT_BG["info"])
    border_color = _CALLOUT_BORDER.get(style, _CALLOUT_BORDER["info"])

    clean_body = _clean_text(text)
    clean_title = _clean_text(title.upper()) if title else None

    start_y = pdf.get_y()
    if start_y > 240:
        pdf.add_page()
        start_y = pdf.get_y()

    line_height = 4.5
    title_height = 6.0 if clean_title else 0.0
    box_w = 190.0

    pdf.set_font("Helvetica", "", 8.5)
    lines = pdf.multi_cell(180, line_height, clean_body, dry_run=True, output="LINES")
    box_h = max(12.0, (len(lines) * line_height) + title_height + 5.0)

    if start_y + box_h > 265:
        pdf.add_page()
        start_y = pdf.get_y()

    pdf.set_fill_color(*bg_color)
    pdf.rect(10, start_y, box_w, box_h, "F")

    # Accent left bar
    pdf.set_fill_color(*border_color)
    pdf.rect(10, start_y, 3, box_h, "F")

    curr_y = start_y + 2.5
    if clean_title:
        pdf.set_xy(16, curr_y)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*border_color)
        pdf.cell(180, 5, clean_title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        curr_y += 5.5

    pdf.set_xy(16, curr_y)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*_DARK_GRAY)
    pdf.multi_cell(180, line_height, clean_body, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(start_y + box_h + 3.5)


def _render_markdown_text(
    pdf: FPDF,
    text: str,
    default_font_size: float = 8.5,
) -> None:
    """Parse lightweight markdown (headers, bullets, bold) and render neatly."""
    if not text:
        return

    clean = _clean_text(text)
    lines = clean.split("\n")

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            pdf.ln(2.0)
            continue

        # Header 3: ### Heading
        if line.startswith("### "):
            pdf.ln(1.5)
            pdf.set_font("Helvetica", "B", default_font_size + 1.0)
            pdf.set_text_color(*_NISKAVA_BLUE)
            pdf.cell(190, 5.5, line[4:].strip(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(0, 0, 0)
            continue

        # Header 2: ## Heading
        if line.startswith("## "):
            pdf.ln(2.0)
            pdf.set_font("Helvetica", "B", default_font_size + 2.0)
            pdf.set_text_color(*_NISKAVA_BLUE)
            pdf.cell(190, 6.0, line[3:].strip(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(0, 0, 0)
            continue

        # Bullet list: - or *
        is_bullet = line.startswith("- ") or line.startswith("* ")
        bullet_indent = 16 if is_bullet else 10
        text_content = line[2:].strip() if is_bullet else line

        if is_bullet:
            pdf.set_font("Helvetica", "B", default_font_size)
            pdf.set_text_color(*_NISKAVA_BLUE)
            pdf.set_x(10)
            pdf.cell(5, 4.5, "-", align="R")

        # Parse inline **bold**
        pdf.set_x(bullet_indent)
        pdf.set_text_color(0, 0, 0)
        width_avail = 190 - (bullet_indent - 10)

        if "**" in text_content:
            parts = text_content.split("**")
            for idx, part in enumerate(parts):
                if not part:
                    continue
                is_bold = (idx % 2 == 1)
                pdf.set_font("Helvetica", "B" if is_bold else "", default_font_size)
                pdf.write(4.5, part)
            pdf.ln(4.5)
        else:
            pdf.set_font("Helvetica", "", default_font_size)
            pdf.multi_cell(width_avail, 4.5, text_content, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(2.5)


def _render_executive_summary(pdf: FPDF, summary: str, title: str = "EXECUTIVE SUMMARY") -> None:
    _section_title(pdf, title)
    _render_markdown_text(pdf, summary or "No analytical summary provided.")


def _has_meaningful_quant_metrics(metrics: Dict[str, Any]) -> bool:
    """Check if metrics contains actual quantitative data rather than empty or all N/A values."""
    if not metrics or not isinstance(metrics, dict):
        return False
    # Check for actual numerical anomaly indicators
    vz = metrics.get("volume_z_score")
    fz = metrics.get("foreign_flow_z_score")
    ret = metrics.get("abnormal_return_pct")
    candles = metrics.get("candles_analyzed")
    anomaly = metrics.get("anomaly_detected")

    valid_vals = [vz, fz, ret, candles]
    meaningful = any(v is not None and str(v).strip().upper() not in ("N/A", "NONE", "") for v in valid_vals)
    return meaningful or bool(anomaly)


def _render_quant_metrics(pdf: FPDF, metrics: Dict[str, Any]) -> None:
    if not _has_meaningful_quant_metrics(metrics):
        return

    _section_title(pdf, "QUANTITATIVE ANOMALY MATRIX  (NumPy Deterministic — Law 1)")

    rows = [
        ("Volume Z-Score (Vz)", str(metrics.get("volume_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Foreign Flow Z-Score (Fz)", str(metrics.get("foreign_flow_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Abnormal Return", f"{metrics.get('abnormal_return_pct', 'N/A')}%" if metrics.get('abnormal_return_pct') is not None else "N/A", ">= 5% -> Anomaly"),
        ("Candles Analyzed", str(metrics.get("candles_analyzed", "N/A")), "Trading days"),
        ("Anomaly Detected", "YES" if metrics.get("anomaly_detected") else "NO", ""),
        ("Latest Anomaly Date", str(metrics.get("latest_anomaly_date", "N/A")), ""),
    ]

    col_w = [75, 45, 70]
    headers = ["Metric", "Value", "Threshold"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 8)
    for i, (label, value, note) in enumerate(rows):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(248, 248, 248)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(label, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(value, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[2], 5.5, f"  {_clean_text(note, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_evidence_matrix(pdf: FPDF, evidence: List[Dict[str, Any]]) -> None:
    if not evidence or not isinstance(evidence, list):
        return

    # Check if there is at least one item with content
    valid_items = [
        item for item in evidence
        if isinstance(item, dict) and any(item.get(k) for k in ("headline", "title", "claim", "snippet"))
    ]
    if not valid_items:
        return

    _section_title(pdf, "EVIDENCE & CAUSALITY MATRIX")

    col_w = [25, 25, 115, 25]
    headers = ["Date", "Status", "Headline", "Confidence"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, item in enumerate(valid_items):
        fill = i % 2 == 0
        status = str(item.get("verification_status", "UNCERTAIN")).upper()
        color = _verification_color(status)
        bg = (248, 248, 248) if fill else (255, 255, 255)

        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(item.get('date', ''), single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(*color)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(status, single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(0, 0, 0)
        headline = _clean_text(str(item.get("headline") or item.get("title") or ""), single_line=True)[:90]
        pdf.cell(col_w[2], 5.5, f"  {headline}", border=1, fill=fill)

        conf = str(item.get("confidence_score", ""))
        pdf.cell(col_w[3], 5.5, f"  {_clean_text(conf, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_news_matrix(pdf: FPDF, news_items: List[Dict[str, Any]]) -> None:
    if not news_items or not isinstance(news_items, list):
        return

    valid_items = [
        item for item in news_items
        if isinstance(item, dict) and any(item.get(k) for k in ("headline", "title", "snippet"))
    ]
    if not valid_items:
        return

    _section_title(pdf, "MARKET NEWS DIGEST & DISCLOSURES")

    col_w = [25, 35, 105, 25]
    headers = ["Date", "Source / Topic", "Verified Headline", "Status"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, item in enumerate(valid_items):
        fill = i % 2 == 0
        status = str(item.get("status") or item.get("sentiment") or "VERIFIED").upper()
        color = _verification_color(status)
        bg = (248, 248, 248) if fill else (255, 255, 255)

        date_str = str(item.get("date") or item.get("published_at") or "")
        source_str = str(item.get("source") or item.get("topic") or "Official")[:18]
        headline = str(item.get("headline") or item.get("title") or "")[:85]

        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(date_str, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(source_str, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[2], 5.5, f"  {_clean_text(headline, single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(*color)
        pdf.cell(col_w[3], 5.5, f"  {_clean_text(status, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_custom_sections(pdf: FPDF, sections: List[Dict[str, Any]]) -> None:
    if not sections or not isinstance(sections, list):
        return

    for sec in sections:
        if not isinstance(sec, dict):
            continue
        heading = sec.get("heading") or sec.get("title") or "ANALYSIS"
        content = sec.get("content") or sec.get("body") or ""
        if not content:
            continue

        _section_title(pdf, str(heading).upper())
        pdf.set_font("Helvetica", "", 8.5)
        clean_content = _clean_text(content)
        pdf.multi_cell(190, 4.5, clean_content, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3.5)


def _render_generic_table(pdf: FPDF, table: Dict[str, Any]) -> None:
    """Render an institutional data table with headers and alternating row shading."""
    if not table or not isinstance(table, dict):
        return

    sec_title = table.get("title") or table.get("heading")
    headers = table.get("headers") or table.get("columns") or []
    raw_rows = table.get("rows") or table.get("data") or []

    # If rows are dicts and headers are empty:
    if not headers and raw_rows and isinstance(raw_rows[0], dict):
        headers = list(raw_rows[0].keys())

    # If headers are dicts: extract name and width
    col_widths_from_headers = None
    if headers and isinstance(headers[0], dict):
        col_widths_from_headers = [h.get("width") for h in headers if "width" in h]
        headers = [h.get("name") or h.get("label") or h.get("title") or str(h) for h in headers]

    headers = [str(h) for h in headers] if headers else []

    if not headers and not raw_rows:
        return

    if sec_title:
        _section_title(pdf, str(sec_title).upper())

    total_w = 190.0
    n_cols = len(headers) if headers else (len(raw_rows[0]) if raw_rows and isinstance(raw_rows[0], (list, tuple)) else 1)
    if n_cols == 0:
        return

    user_widths = table.get("col_widths") or table.get("widths") or col_widths_from_headers
    if user_widths and len(user_widths) == n_cols:
        try:
            parsed_w = [float(w) for w in user_widths]
            sum_w = sum(parsed_w)
            if abs(sum_w - total_w) < 1.0:
                col_w = parsed_w
            elif sum_w > 0:
                scale = total_w / sum_w
                col_w = [w * scale for w in parsed_w]
            else:
                col_w = [total_w / n_cols] * n_cols
        except Exception:
            col_w = [total_w / n_cols] * n_cols
    else:
        col_w = [total_w / n_cols] * n_cols

    if pdf.get_y() > 250:
        pdf.add_page()

    # Table Header
    if headers:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(*_NISKAVA_BLUE)
        pdf.set_text_color(255, 255, 255)
        for h, w in zip(headers, col_w):
            clean_h = _clean_text(str(h), single_line=True)
            pdf.cell(w, 6, f"  {clean_h}", border=1, fill=True)
        pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, raw_row in enumerate(raw_rows):
        if isinstance(raw_row, dict):
            row_cells = [raw_row.get(h, "") for h in headers]
        elif isinstance(raw_row, (list, tuple)):
            row_cells = list(raw_row)
        else:
            row_cells = [raw_row]

        if len(row_cells) < n_cols:
            row_cells = list(row_cells) + [""] * (n_cols - len(row_cells))
        elif len(row_cells) > n_cols:
            row_cells = row_cells[:n_cols]

        fill = (i % 2 == 0)
        bg = (248, 248, 248) if fill else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(0, 0, 0)

        for cell_val, w in zip(row_cells, col_w):
            clean_val = _clean_text(str(cell_val) if cell_val is not None else "", single_line=True)
            max_chars = max(10, int(w * 1.5))
            if len(clean_val) > max_chars:
                clean_val = clean_val[:max_chars - 3] + "..."
            pdf.cell(w, 5.5, f"  {clean_val}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_key_value_grid(
    pdf: FPDF,
    kv_data: Dict[str, Any],
    title: Optional[str] = None,
) -> None:
    """Render a structured key-value grid (e.g. valuation multiples or company profile)."""
    if not kv_data or not isinstance(kv_data, dict):
        return

    sec_title = title or kv_data.get("title") or kv_data.get("heading")

    items_source = (
        kv_data.get("items")
        or kv_data.get("data")
        or kv_data.get("metrics")
        or kv_data.get("values")
    )

    pairs: List[tuple[str, str]] = []

    if isinstance(items_source, dict):
        for k, v in items_source.items():
            if str(k).lower() not in ("title", "heading", "type", "cols"):
                pairs.append((str(k), str(v)))
    elif isinstance(items_source, list):
        for entry in items_source:
            if isinstance(entry, dict):
                k = entry.get("key") or entry.get("label") or entry.get("name")
                v = entry.get("value") or entry.get("val")
                if k is not None and v is not None:
                    pairs.append((str(k), str(v)))
                else:
                    for k_sub, v_sub in entry.items():
                        if str(k_sub).lower() not in ("title", "heading", "type"):
                            pairs.append((str(k_sub), str(v_sub)))
            elif isinstance(entry, (list, tuple)) and len(entry) >= 2:
                pairs.append((str(entry[0]), str(entry[1])))
    else:
        for k, v in kv_data.items():
            if str(k).lower() not in ("title", "heading", "type", "cols", "items", "data", "metrics", "values"):
                pairs.append((str(k), str(v)))

    if not pairs:
        return

    if sec_title:
        _section_title(pdf, str(sec_title).upper())

    if pdf.get_y() > 250:
        pdf.add_page()

    cols = int(kv_data.get("cols", 2))
    total_w = 190.0

    if cols == 1:
        k_w = 65.0
        v_w = 125.0
        for i, (k, v) in enumerate(pairs):
            fill = (i % 2 == 0)
            bg = (248, 248, 248) if fill else (255, 255, 255)
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_DARK_GRAY)
            clean_k = _clean_text(k, single_line=True)
            max_k = int(k_w * 1.5)
            if len(clean_k) > max_k:
                clean_k = clean_k[:max_k - 3] + "..."
            pdf.cell(k_w, 5.5, f"  {clean_k}", border=1, fill=fill)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(0, 0, 0)
            clean_v = _clean_text(v, single_line=True)
            max_v = int(v_w * 1.5)
            if len(clean_v) > max_v:
                clean_v = clean_v[:max_v - 3] + "..."
            pdf.cell(v_w, 5.5, f"  {clean_v}", border=1, fill=fill)
            pdf.ln()
    else:
        col_pair_w = total_w / 2.0  # 95.0mm
        k_w = 42.0
        v_w = col_pair_w - k_w      # 53.0mm

        for idx in range(0, len(pairs), 2):
            k1, v1 = pairs[idx]
            has_second = (idx + 1 < len(pairs))
            k2, v2 = pairs[idx + 1] if has_second else ("", "")

            row_idx = idx // 2
            fill = (row_idx % 2 == 0)
            bg = (248, 248, 248) if fill else (255, 255, 255)

            # Left pair
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*_DARK_GRAY)
            clean_k1 = _clean_text(k1, single_line=True)
            if len(clean_k1) > int(k_w * 1.5):
                clean_k1 = clean_k1[:int(k_w * 1.5) - 3] + "..."
            pdf.cell(k_w, 5.5, f"  {clean_k1}", border=1, fill=fill)

            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(0, 0, 0)
            clean_v1 = _clean_text(v1, single_line=True)
            if len(clean_v1) > int(v_w * 1.5):
                clean_v1 = clean_v1[:int(v_w * 1.5) - 3] + "..."
            pdf.cell(v_w, 5.5, f"  {clean_v1}", border=1, fill=fill)

            # Right pair
            if has_second:
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.set_text_color(*_DARK_GRAY)
                clean_k2 = _clean_text(k2, single_line=True)
                if len(clean_k2) > int(k_w * 1.5):
                    clean_k2 = clean_k2[:int(k_w * 1.5) - 3] + "..."
                pdf.cell(k_w, 5.5, f"  {clean_k2}", border=1, fill=fill)

                pdf.set_font("Helvetica", "", 7.5)
                pdf.set_text_color(0, 0, 0)
                clean_v2 = _clean_text(v2, single_line=True)
                if len(clean_v2) > int(v_w * 1.5):
                    clean_v2 = clean_v2[:int(v_w * 1.5) - 3] + "..."
                pdf.cell(v_w, 5.5, f"  {clean_v2}", border=1, fill=fill)
            else:
                pdf.cell(k_w + v_w, 5.5, "", border=1, fill=fill)

            pdf.ln()

    pdf.ln(3.5)


def _render_block(pdf: FPDF, block: Dict[str, Any]) -> None:
    """Render a single content block based on its block type."""
    if not block or not isinstance(block, dict):
        return

    b_type = str(block.get("type", "")).lower().strip().replace("-", "_")

    if b_type == "callout":
        text = str(block.get("text") or block.get("content") or block.get("body") or "")
        title = block.get("title") or block.get("heading")
        style = str(block.get("style", "info")).lower()
        _render_callout_box(pdf, text=text, title=title, style=style)

    elif b_type in ("markdown", "text", "summary"):
        title = block.get("title") or block.get("heading")
        if title:
            _section_title(pdf, str(title).upper())
        content = str(block.get("content") or block.get("text") or block.get("body") or block.get("summary") or "")
        _render_markdown_text(pdf, content)

    elif b_type in ("table", "generic_table"):
        table_data = block.get("table")
        if isinstance(table_data, dict):
            t_copy = dict(table_data)
            if "title" not in t_copy and (block.get("title") or block.get("heading")):
                t_copy["title"] = block.get("title") or block.get("heading")
            _render_generic_table(pdf, t_copy)
        else:
            _render_generic_table(pdf, block)

    elif b_type in ("key_value", "key_values", "metrics_grid"):
        title = block.get("title") or block.get("heading")
        data = block.get("data")
        items = block.get("items")
        if isinstance(data, dict):
            _render_key_value_grid(pdf, data, title=title)
        elif isinstance(items, (dict, list)):
            _render_key_value_grid(pdf, block, title=title)
        else:
            _render_key_value_grid(pdf, block, title=title)

    elif b_type in ("quant_metrics", "quant", "metrics"):
        metrics = block.get("metrics") or block.get("data") or block
        _render_quant_metrics(pdf, metrics)

    elif b_type in ("evidence_matrix", "evidence"):
        evidence = block.get("evidence") or block.get("items") or block.get("data") or []
        _render_evidence_matrix(pdf, evidence)

    elif b_type in ("news_matrix", "news", "news_items"):
        news_items = block.get("news_items") or block.get("items") or block.get("data") or []
        _render_news_matrix(pdf, news_items)


def _detect_report_type(ticker: str, params: Dict[str, Any]) -> str:
    explicit = params.get("report_type")
    if explicit:
        return str(explicit).upper().strip()

    t_upper = ticker.upper()
    macro_tickers = ("MARKET", "IDX MARKET", "IHSG", "MACRO", "GENERAL", "NEWS", "IDX")
    if t_upper in macro_tickers:
        return "MARKET_NEWS_BRIEF"

    metrics = params.get("metrics") or {}
    if _has_meaningful_quant_metrics(metrics):
        return "TICKER_INVESTIGATION"

    if params.get("news_items"):
        return "MARKET_NEWS_BRIEF"

    blocks = params.get("blocks") or []
    if blocks:
        for b in blocks:
            b_type = str(b.get("type", "")).lower()
            if "quant" in b_type:
                return "TICKER_INVESTIGATION"
            if "news" in b_type:
                return "MARKET_NEWS_BRIEF"
        return "CUSTOM_RESEARCH"

    if params.get("sections"):
        return "CUSTOM_RESEARCH"

    return "TICKER_INVESTIGATION"


def render_investigation_pdf(
    params: Dict[str, Any],
    output_dir: Optional[Path] = None,
) -> str:
    """Render a dynamic, section-driven investigation or market intelligence report to PDF.

    Supports ordered dynamic blocks (`params["blocks"]`) or legacy section keys.

    Args:
        params: Dict with optional keys: ticker (str), title (str), summary (str),
                metrics (dict), evidence (list[dict]), news_items (list[dict]),
                sections (list[dict]), blocks (list[dict]), custom_tables (list[dict]),
                report_type (str), session_id (str).
        output_dir: Directory to write the PDF. Defaults to ~/.niskava/reports/.

    Returns:
        Absolute path string of the written PDF file.
    """
    raw_ticker = str(params.get("ticker", "")).strip()
    ticker = raw_ticker.upper() if raw_ticker else "MARKET"

    session_id = str(params.get("session_id", "000000"))
    report_type = _detect_report_type(ticker, params)

    default_title = (
        f"{ticker} Investigation Audit Trail"
        if report_type == "TICKER_INVESTIGATION"
        else f"IDX Daily Market Intelligence Brief — {ticker}"
    )
    title = str(params.get("title") or default_title)
    summary = str(params.get("summary", ""))
    metrics: Dict[str, Any] = params.get("metrics") or {}
    evidence: List[Dict[str, Any]] = params.get("evidence") or []
    news_items: List[Dict[str, Any]] = params.get("news_items") or []
    sections: List[Dict[str, Any]] = params.get("sections") or []

    # Resolve output directory (Law 4: local-first)
    if output_dir is None:
        output_dir = Path.home() / ".niskava" / "reports"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today_str = date.today().strftime("%Y%m%d")
    session_short = _sanitize_session_short(session_id)
    safe_ticker = "".join(c for c in ticker if c.isalnum() or c == "_")
    filename = f"NISKAVA_{safe_ticker}_{today_str}_{session_short}_audit.pdf"
    output_path = output_dir / filename

    # Build PDF
    pdf = _NiskavaReportPDF(ticker=ticker, session_id=session_id)
    pdf.set_compression(False)
    pdf.set_auto_page_break(auto=True, margin=26)
    pdf.add_page()

    # Document Title Block
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.cell(190, 8, _clean_text(title), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(*_DARK_GRAY)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(
        190,
        4.5,
        _clean_text(f"Generated: {generated_at}  |  Session ID: {session_id}  |  Type: {report_type}"),
        align="C",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
    )
    pdf.ln(3.5)

    # Dynamic ordered blocks or backward-compatible legacy fallback
    raw_blocks = params.get("blocks")
    if raw_blocks and isinstance(raw_blocks, list):
        for block in raw_blocks:
            _render_block(pdf, block)
    else:
        # Build backward-compatible blocks list from legacy keys
        legacy_blocks: List[Dict[str, Any]] = [
            {
                "type": "summary",
                "title": "EXECUTIVE SUMMARY",
                "content": summary or "No analytical summary provided.",
            }
        ]
        if _has_meaningful_quant_metrics(metrics):
            legacy_blocks.append({
                "type": "quant_metrics",
                "metrics": metrics,
            })
        if evidence:
            legacy_blocks.append({
                "type": "evidence_matrix",
                "evidence": evidence,
            })
        if news_items:
            legacy_blocks.append({
                "type": "news_matrix",
                "news_items": news_items,
            })
        custom_tables = params.get("custom_tables") or []
        if custom_tables:
            if isinstance(custom_tables, list):
                for tbl in custom_tables:
                    if isinstance(tbl, dict):
                        tbl_b = dict(tbl)
                        tbl_b.setdefault("type", "table")
                        legacy_blocks.append(tbl_b)
            elif isinstance(custom_tables, dict):
                tbl_b = dict(custom_tables)
                tbl_b.setdefault("type", "table")
                legacy_blocks.append(tbl_b)
        if sections:
            for sec in sections:
                if isinstance(sec, dict):
                    legacy_blocks.append({
                        "type": "markdown",
                        "title": str(sec.get("heading") or sec.get("title") or "ANALYSIS").upper(),
                        "content": sec.get("content") or sec.get("body") or "",
                    })

        for block in legacy_blocks:
            _render_block(pdf, block)

    pdf.output(str(output_path))
    return str(output_path.resolve())

