"""Deterministic PDF renderer for Niskava investigation audit trail reports.

Uses fpdf2 (pure-Python, zero C-extensions) to produce institutional-grade PDF
documents. This module has exactly one public entry point:

    render_investigation_pdf(params: Dict[str, Any], output_dir: Optional[Path] = None) -> str

All data must be pre-computed and passed in via `params`. No LLM, no API calls.
"""

from __future__ import annotations

import os
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ─── Constants ───────────────────────────────────────────────────────────────

NON_ADVISORY_DISCLAIMER: str = (
    "NON-ADVISORY DISCLAIMER: This document is an autonomous market intelligence audit "
    "trail generated by Niskava Agent. It does NOT constitute financial advice, "
    "investment recommendations, or solicitation to buy or sell any security. "
    "All findings are strictly informational and investigative in nature."
)

_NISKAVA_BLUE = (13, 71, 161)      # Institutional Navy Blue #0D47A1
_SUPPORTED_GREEN = (27, 94, 32)     # Emerald Green #1B5E20
_UNCERTAIN_ORANGE = (230, 81, 0)    # Amber/Orange #E65100
_CONTRADICTED_RED = (183, 28, 28)   # Crimson Red #B71C1C
_LIGHT_GRAY = (245, 245, 245)
_DARK_GRAY = (66, 66, 66)


def _clean_text(text: Any) -> str:
    """Sanitize string for core Helvetica Latin-1 font in fpdf2."""
    if text is None:
        return ""
    s = str(text)
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--",
        "\u2026": "...", "\u00a0": " ",
        "σ": "sigma", "≥": ">=", "≤": "<=", "±": "+/-",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode("latin-1", errors="replace").decode("latin-1")


def _sanitize_session_short(session_id: Optional[str]) -> str:
    """Extract a 6-character uppercase alphanumeric session suffix. Defaults to '000000'."""
    if not session_id:
        return "000000"
    clean = "".join(c for c in str(session_id) if c.isalnum()).upper()
    if not clean:
        return "000000"
    if len(clean) >= 6:
        return clean[-6:]
    return clean.rjust(6, "0")


def _verification_color(status: str) -> tuple[int, int, int]:
    mapping = {
        "SUPPORTED": _SUPPORTED_GREEN,
        "UNCERTAIN": _UNCERTAIN_ORANGE,
        "CONTRADICTED": _CONTRADICTED_RED,
    }
    return mapping.get(status.upper(), _DARK_GRAY)


class _NiskavaReportPDF(FPDF):
    """FPDF subclass with Niskava header and mandatory non-advisory footer on every page."""

    def __init__(self, ticker: str, session_id: str) -> None:
        super().__init__()
        self._ticker = ticker
        self._session_id = session_id

    def header(self) -> None:
        # Blue banner across top
        self.set_fill_color(*_NISKAVA_BLUE)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10.5)
        self.set_xy(10, 4)
        clean_header = _clean_text(
            f"NISKAVA MARKET INTELLIGENCE  |  {self._ticker}  |  {self._session_id}"
        )
        self.cell(190, 10, clean_header, align="L")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self) -> None:
        self.set_y(-22)
        # Disclaimer callout box
        self.set_fill_color(255, 243, 224)
        self.set_draw_color(230, 81, 0)
        self.rect(10, self.get_y(), 190, 14, "FD")
        self.set_font("Helvetica", "", 6.5)
        self.set_text_color(*_UNCERTAIN_ORANGE)
        self.set_xy(12, self.get_y() + 1)
        self.multi_cell(186, 3.5, NON_ADVISORY_DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(150, 150, 150)
        self.set_font("Helvetica", "", 7)
        self.set_xy(10, self.get_y() + 1)
        self.cell(190, 4, f"Generated by Niskava Agent  |  Page {self.page_no()}", align="R")


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.set_fill_color(*_LIGHT_GRAY)
    pdf.cell(190, 6.5, f"  {_clean_text(title)}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1.5)


def _render_executive_summary(pdf: FPDF, summary: str) -> None:
    _section_title(pdf, "1. EXECUTIVE SUMMARY")
    pdf.set_font("Helvetica", "", 8.5)
    clean_summary = _clean_text(summary or "No analytical summary provided.")
    pdf.multi_cell(190, 4.5, clean_summary, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3.5)


def _render_quant_metrics(pdf: FPDF, metrics: Dict[str, Any]) -> None:
    _section_title(pdf, "2. QUANTITATIVE ANOMALY MATRIX  (NumPy Deterministic — Law 1)")

    rows = [
        ("Volume Z-Score (Vz)", str(metrics.get("volume_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Foreign Flow Z-Score (Fz)", str(metrics.get("foreign_flow_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Abnormal Return", f"{metrics.get('abnormal_return_pct', 'N/A')}%", ">= 5% -> Anomaly"),
        ("Candles Analyzed", str(metrics.get("candles_analyzed", "N/A")), "Trading days"),
        ("Anomaly Detected", "YES" if metrics.get("anomaly_detected") else "NO", ""),
        ("Latest Anomaly Date", str(metrics.get("latest_anomaly_date", "N/A")), ""),
    ]

    col_w = [75, 45, 70]
    headers = ["Metric", "Value", "Threshold"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 8)
    for i, (label, value, note) in enumerate(rows):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(248, 248, 248)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(label)}", border=1, fill=fill)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(value)}", border=1, fill=fill)
        pdf.cell(col_w[2], 5.5, f"  {_clean_text(note)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_evidence_matrix(pdf: FPDF, evidence: List[Dict[str, Any]]) -> None:
    _section_title(pdf, "3. EVIDENCE & CAUSALITY MATRIX")

    if not evidence:
        pdf.set_font("Helvetica", "I", 8.5)
        pdf.cell(190, 6, "  No external evidence items correlated in this session.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)
        return

    col_w = [25, 25, 115, 25]
    headers = ["Date", "Status", "Headline", "Confidence"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, item in enumerate(evidence):
        fill = i % 2 == 0
        status = str(item.get("verification_status", "UNCERTAIN")).upper()
        color = _verification_color(status)
        bg = (248, 248, 248) if fill else (255, 255, 255)

        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(item.get('date', ''))}", border=1, fill=fill)

        pdf.set_text_color(*color)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(status)}", border=1, fill=fill)

        pdf.set_text_color(0, 0, 0)
        headline = _clean_text(str(item.get("headline", "")))[:90]
        pdf.cell(col_w[2], 5.5, f"  {headline}", border=1, fill=fill)

        conf = str(item.get("confidence_score", ""))
        pdf.cell(col_w[3], 5.5, f"  {_clean_text(conf)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def render_investigation_pdf(
    params: Dict[str, Any],
    output_dir: Optional[Path] = None,
) -> str:
    """Render an investigation audit trail to a PDF file and return its absolute path.

    Args:
        params: Dict with keys: ticker (str), title (str), summary (str),
                metrics (dict), evidence (list[dict]), session_id (str, optional).
        output_dir: Directory to write the PDF. Defaults to ~/.niskava/reports/.
                    Created automatically if it does not exist.

    Returns:
        Absolute path string of the written PDF file.

    Raises:
        ValueError: If `ticker` is missing or empty in params.
    """
    ticker = str(params.get("ticker", "")).upper().strip()
    if not ticker:
        raise ValueError("render_investigation_pdf: 'ticker' is required in params.")

    session_id = str(params.get("session_id", "000000"))
    title = str(params.get("title", f"{ticker} Investigation Audit Trail"))
    summary = str(params.get("summary", ""))
    metrics: Dict[str, Any] = params.get("metrics", {})
    evidence: List[Dict[str, Any]] = params.get("evidence", [])

    # Resolve output directory (Law 4: local-first)
    if output_dir is None:
        output_dir = Path.home() / ".niskava" / "reports"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today_str = date.today().strftime("%Y%m%d")
    session_short = _sanitize_session_short(session_id)
    filename = f"NISKAVA_{ticker}_{today_str}_{session_short}_audit.pdf"
    output_path = output_dir / filename

    # Build PDF with compression off so streams are inspectable
    pdf = _NiskavaReportPDF(ticker=ticker, session_id=session_id)
    pdf.set_compression(False)
    pdf.set_auto_page_break(auto=True, margin=26)
    pdf.add_page()

    # Document Title Block
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.cell(190, 8, _clean_text(title), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(*_DARK_GRAY)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(190, 4.5, _clean_text(f"Generated: {generated_at}  |  Session ID: {session_id}"), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3.5)

    # Core Sections
    _render_executive_summary(pdf, summary)
    _render_quant_metrics(pdf, metrics)
    _render_evidence_matrix(pdf, evidence)

    pdf.output(str(output_path))
    return str(output_path.resolve())
