"""Deterministic PDF renderer for Niskava investigation audit trail reports.

Uses fpdf2 (pure-Python, zero C-extensions) to produce institutional-grade PDF
documents. This module has exactly one public entry point:

    render_investigation_pdf(params: Dict[str, Any], output_dir: Optional[Path] = None) -> str

All data must be pre-computed and passed in via `params`. No LLM, no API calls.
"""

from __future__ import annotations

import os
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ─── Constants ───────────────────────────────────────────────────────────────

NON_ADVISORY_DISCLAIMER: str = (
    "NON-ADVISORY DISCLAIMER: This document is an autonomous market intelligence audit "
    "trail generated by Niskava Agent. It does NOT constitute financial advice, "
    "investment recommendations, or solicitation to buy or sell any security. "
    "All findings are strictly informational and investigative in nature."
)

_NISKAVA_BLUE = (13, 71, 161)      # Institutional Navy Blue #0D47A1
_SUPPORTED_GREEN = (27, 94, 32)     # Emerald Green #1B5E20
_UNCERTAIN_ORANGE = (230, 81, 0)    # Amber/Orange #E65100
_CONTRADICTED_RED = (183, 28, 28)   # Crimson Red #B71C1C
_LIGHT_GRAY = (245, 245, 245)
_DARK_GRAY = (66, 66, 66)


def _clean_text(text: Any, single_line: bool = False) -> str:
    """Sanitize string for core Helvetica Latin-1 font in fpdf2."""
    if text is None:
        return ""
    s = str(text)
    if single_line:
        s = s.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--",
        "\u2026": "...", "\u00a0": " ",
        "\u2022": "-", "\u2023": ">", "\u25aa": "-",
        "\u2192": "->", "\u2190": "<-", "\u2191": "+", "\u2193": "-",
        "\u2248": "~", "\u2260": "!=",
        "σ": "sigma", "≥": ">=", "≤": "<=", "±": "+/-",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode("latin-1", errors="replace").decode("latin-1")


def _sanitize_session_short(session_id: Optional[str]) -> str:
    """Extract a 6-character uppercase alphanumeric session suffix. Defaults to '000000'."""
    if not session_id:
        return "000000"
    clean = "".join(c for c in str(session_id) if c.isalnum()).upper()
    if not clean:
        return "000000"
    if len(clean) >= 6:
        return clean[-6:]
    return clean.rjust(6, "0")


def _verification_color(status: str) -> tuple[int, int, int]:
    mapping = {
        "SUPPORTED": _SUPPORTED_GREEN,
        "UNCERTAIN": _UNCERTAIN_ORANGE,
        "CONTRADICTED": _CONTRADICTED_RED,
    }
    return mapping.get(status.upper(), _DARK_GRAY)


class _NiskavaReportPDF(FPDF):
    """FPDF subclass with Niskava header and mandatory non-advisory footer on every page."""

    def __init__(self, ticker: str, session_id: str) -> None:
        super().__init__()
        self._ticker = ticker
        self._session_id = session_id

    def header(self) -> None:
        # Blue banner across top
        self.set_fill_color(*_NISKAVA_BLUE)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10.5)
        self.set_xy(10, 4)
        clean_header = _clean_text(
            f"NISKAVA MARKET INTELLIGENCE  |  {self._ticker}  |  {self._session_id}"
        )
        self.cell(190, 10, clean_header, align="L")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self) -> None:
        self.set_y(-22)
        # Disclaimer callout box
        self.set_fill_color(255, 243, 224)
        self.set_draw_color(230, 81, 0)
        self.rect(10, self.get_y(), 190, 14, "FD")
        self.set_font("Helvetica", "", 6.5)
        self.set_text_color(*_UNCERTAIN_ORANGE)
        self.set_xy(12, self.get_y() + 1)
        self.multi_cell(186, 3.5, NON_ADVISORY_DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(150, 150, 150)
        self.set_font("Helvetica", "", 7)
        self.set_xy(10, self.get_y() + 1)
        self.cell(190, 4, f"Generated by Niskava Agent  |  Page {self.page_no()}", align="R")


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.set_fill_color(*_LIGHT_GRAY)
    pdf.cell(190, 6.5, f"  {_clean_text(title)}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1.5)


def _render_executive_summary(pdf: FPDF, summary: str, title: str = "EXECUTIVE SUMMARY") -> None:
    _section_title(pdf, title)
    pdf.set_font("Helvetica", "", 8.5)
    clean_summary = _clean_text(summary or "No analytical summary provided.")
    pdf.multi_cell(190, 4.5, clean_summary, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3.5)


def _has_meaningful_quant_metrics(metrics: Dict[str, Any]) -> bool:
    """Check if metrics contains actual quantitative data rather than empty or all N/A values."""
    if not metrics or not isinstance(metrics, dict):
        return False
    # Check for actual numerical anomaly indicators
    vz = metrics.get("volume_z_score")
    fz = metrics.get("foreign_flow_z_score")
    ret = metrics.get("abnormal_return_pct")
    candles = metrics.get("candles_analyzed")
    anomaly = metrics.get("anomaly_detected")

    valid_vals = [vz, fz, ret, candles]
    meaningful = any(v is not None and str(v).strip().upper() not in ("N/A", "NONE", "") for v in valid_vals)
    return meaningful or bool(anomaly)


def _render_quant_metrics(pdf: FPDF, metrics: Dict[str, Any]) -> None:
    if not _has_meaningful_quant_metrics(metrics):
        return

    _section_title(pdf, "QUANTITATIVE ANOMALY MATRIX  (NumPy Deterministic — Law 1)")

    rows = [
        ("Volume Z-Score (Vz)", str(metrics.get("volume_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Foreign Flow Z-Score (Fz)", str(metrics.get("foreign_flow_z_score", "N/A")), "sigma >= 2.5 -> Anomaly"),
        ("Abnormal Return", f"{metrics.get('abnormal_return_pct', 'N/A')}%" if metrics.get('abnormal_return_pct') is not None else "N/A", ">= 5% -> Anomaly"),
        ("Candles Analyzed", str(metrics.get("candles_analyzed", "N/A")), "Trading days"),
        ("Anomaly Detected", "YES" if metrics.get("anomaly_detected") else "NO", ""),
        ("Latest Anomaly Date", str(metrics.get("latest_anomaly_date", "N/A")), ""),
    ]

    col_w = [75, 45, 70]
    headers = ["Metric", "Value", "Threshold"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 8)
    for i, (label, value, note) in enumerate(rows):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(248, 248, 248)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(label, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(value, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[2], 5.5, f"  {_clean_text(note, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_evidence_matrix(pdf: FPDF, evidence: List[Dict[str, Any]]) -> None:
    if not evidence or not isinstance(evidence, list):
        return

    # Check if there is at least one item with content
    valid_items = [
        item for item in evidence
        if isinstance(item, dict) and any(item.get(k) for k in ("headline", "title", "claim", "snippet"))
    ]
    if not valid_items:
        return

    _section_title(pdf, "EVIDENCE & CAUSALITY MATRIX")

    col_w = [25, 25, 115, 25]
    headers = ["Date", "Status", "Headline", "Confidence"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, item in enumerate(valid_items):
        fill = i % 2 == 0
        status = str(item.get("verification_status", "UNCERTAIN")).upper()
        color = _verification_color(status)
        bg = (248, 248, 248) if fill else (255, 255, 255)

        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(item.get('date', ''), single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(*color)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(status, single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(0, 0, 0)
        headline = _clean_text(str(item.get("headline") or item.get("title") or ""), single_line=True)[:90]
        pdf.cell(col_w[2], 5.5, f"  {headline}", border=1, fill=fill)

        conf = str(item.get("confidence_score", ""))
        pdf.cell(col_w[3], 5.5, f"  {_clean_text(conf, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_news_matrix(pdf: FPDF, news_items: List[Dict[str, Any]]) -> None:
    if not news_items or not isinstance(news_items, list):
        return

    valid_items = [
        item for item in news_items
        if isinstance(item, dict) and any(item.get(k) for k in ("headline", "title", "snippet"))
    ]
    if not valid_items:
        return

    _section_title(pdf, "MARKET NEWS DIGEST & DISCLOSURES")

    col_w = [25, 35, 105, 25]
    headers = ["Date", "Source / Topic", "Verified Headline", "Status"]

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NISKAVA_BLUE)
    pdf.set_text_color(255, 255, 255)
    for header, w in zip(headers, col_w):
        pdf.cell(w, 6, f"  {header}", border=1, fill=True)
    pdf.ln()

    # Table Data
    pdf.set_font("Helvetica", "", 7.5)
    for i, item in enumerate(valid_items):
        fill = i % 2 == 0
        status = str(item.get("status") or item.get("sentiment") or "VERIFIED").upper()
        color = _verification_color(status)
        bg = (248, 248, 248) if fill else (255, 255, 255)

        date_str = str(item.get("date") or item.get("published_at") or "")
        source_str = str(item.get("source") or item.get("topic") or "Official")[:18]
        headline = str(item.get("headline") or item.get("title") or "")[:85]

        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(*bg)
        pdf.cell(col_w[0], 5.5, f"  {_clean_text(date_str, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[1], 5.5, f"  {_clean_text(source_str, single_line=True)}", border=1, fill=fill)
        pdf.cell(col_w[2], 5.5, f"  {_clean_text(headline, single_line=True)}", border=1, fill=fill)

        pdf.set_text_color(*color)
        pdf.cell(col_w[3], 5.5, f"  {_clean_text(status, single_line=True)}", border=1, fill=fill)
        pdf.ln()

    pdf.ln(3.5)


def _render_custom_sections(pdf: FPDF, sections: List[Dict[str, Any]]) -> None:
    if not sections or not isinstance(sections, list):
        return

    for sec in sections:
        if not isinstance(sec, dict):
            continue
        heading = sec.get("heading") or sec.get("title") or "ANALYSIS"
        content = sec.get("content") or sec.get("body") or ""
        if not content:
            continue

        _section_title(pdf, str(heading).upper())
        pdf.set_font("Helvetica", "", 8.5)
        clean_content = _clean_text(content)
        pdf.multi_cell(190, 4.5, clean_content, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3.5)


def _detect_report_type(ticker: str, params: Dict[str, Any]) -> str:
    explicit = params.get("report_type")
    if explicit:
        return str(explicit).upper().strip()

    t_upper = ticker.upper()
    macro_tickers = ("MARKET", "IDX MARKET", "IHSG", "MACRO", "GENERAL", "NEWS", "IDX")
    if t_upper in macro_tickers:
        return "MARKET_NEWS_BRIEF"

    metrics = params.get("metrics") or {}
    if _has_meaningful_quant_metrics(metrics):
        return "TICKER_INVESTIGATION"

    if params.get("news_items"):
        return "MARKET_NEWS_BRIEF"

    if params.get("sections"):
        return "CUSTOM_RESEARCH"

    return "TICKER_INVESTIGATION"


def render_investigation_pdf(
    params: Dict[str, Any],
    output_dir: Optional[Path] = None,
) -> str:
    """Render a dynamic, section-driven investigation or market intelligence report to PDF.

    Args:
        params: Dict with optional keys: ticker (str), title (str), summary (str),
                metrics (dict), evidence (list[dict]), news_items (list[dict]),
                sections (list[dict]), report_type (str), session_id (str).
        output_dir: Directory to write the PDF. Defaults to ~/.niskava/reports/.

    Returns:
        Absolute path string of the written PDF file.
    """
    raw_ticker = str(params.get("ticker", "")).strip()
    ticker = raw_ticker.upper() if raw_ticker else "MARKET"

    session_id = str(params.get("session_id", "000000"))
    report_type = _detect_report_type(ticker, params)

    default_title = (
        f"{ticker} Investigation Audit Trail"
        if report_type == "TICKER_INVESTIGATION"
        else f"IDX Daily Market Intelligence Brief — {ticker}"
    )
    title = str(params.get("title") or default_title)
    summary = str(params.get("summary", ""))
    metrics: Dict[str, Any] = params.get("metrics") or {}
    evidence: List[Dict[str, Any]] = params.get("evidence") or []
    news_items: List[Dict[str, Any]] = params.get("news_items") or []
    sections: List[Dict[str, Any]] = params.get("sections") or []

    # Resolve output directory (Law 4: local-first)
    if output_dir is None:
        output_dir = Path.home() / ".niskava" / "reports"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today_str = date.today().strftime("%Y%m%d")
    session_short = _sanitize_session_short(session_id)
    safe_ticker = "".join(c for c in ticker if c.isalnum() or c == "_")
    filename = f"NISKAVA_{safe_ticker}_{today_str}_{session_short}_audit.pdf"
    output_path = output_dir / filename

    # Build PDF
    pdf = _NiskavaReportPDF(ticker=ticker, session_id=session_id)
    pdf.set_compression(False)
    pdf.set_auto_page_break(auto=True, margin=26)
    pdf.add_page()

    # Document Title Block
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_NISKAVA_BLUE)
    pdf.cell(190, 8, _clean_text(title), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(*_DARK_GRAY)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(
        190,
        4.5,
        _clean_text(f"Generated: {generated_at}  |  Session ID: {session_id}  |  Type: {report_type}"),
        align="C",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
    )
    pdf.ln(3.5)

    # Section 1: Executive Summary
    _render_executive_summary(pdf, summary)

    # Dynamic Section 2: Quantitative Matrix (only if actual metrics exist)
    if _has_meaningful_quant_metrics(metrics):
        _render_quant_metrics(pdf, metrics)

    # Dynamic Section 3: Evidence Matrix (if correlation evidence exists)
    _render_evidence_matrix(pdf, evidence)

    # Dynamic Section 4: Market News Digest (if news_items provided)
    _render_news_matrix(pdf, news_items)

    # Dynamic Section 5: Custom Analysis Sections
    _render_custom_sections(pdf, sections)

    pdf.output(str(output_path))
    return str(output_path.resolve())

